version: '3.8'
services:
  multiplayer-game:
    build: .
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - game-network
    # не нужно пробрасывать порты наружу, т.к. доступ через ngrok
    # но можно оставить для локальной отладки:
    ports:
      - "3000:3000"
    restart: unless-stopped

  ngrok:
    image: wernight/ngrok:latest
    depends_on:
      - multiplayer-game
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
      NGROK_PORT: multiplayer-game:3000
    restart: unless-stopped
    networks:
      - game-network

networks:
  game-network:
    driver: bridge
