version: '3.8'
services:
  multiplayer-game:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - game-network

networks:
  game-network:
    driver: bridge

volumes:
  game-data: